CREATE TABLE Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CVs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE PersonalInformation (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cv_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  FOREIGN KEY (cv_id) REFERENCES CVs(id)
);

CREATE TABLE Education (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cv_id INT NOT NULL,
  degree VARCHAR(100) NOT NULL,
  institution VARCHAR(100) NOT NULL,
  FOREIGN KEY (cv_id) REFERENCES CVs(id)
);

CREATE TABLE WorkExperience (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cv_id INT NOT NULL,
  job_title VARCHAR(100) NOT NULL,
  company VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  FOREIGN KEY (cv_id) REFERENCES CVs(id)
);

CREATE TABLE Skills (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cv_id INT NOT NULL,
  skill_name VARCHAR(100) NOT NULL,
  FOREIGN KEY (cv_id) REFERENCES CVs(id)
);
